### ISSUE TITLE
[BUG] extra requirements for same subjects and sessions across pipelines seems too restrictive

### ISSUE THREAD

**Issue by Remi-Gau** [neurobagel/digest#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

I would expect the bagel.csv I attached to work with the dashboard.

[bagel.zip](https://github.com/neurobagel/proc_dash/files/11644406/bagel.zip)

### Error message

Getting the following error.

Error: The pipelines in bagel.csv do not have the same number of subjects and sessions. Please try again.

### How to reproduce

try to use the bagel.csv attached

### Anything else?

[bagel.zip](https://github.com/neurobagel/proc_dash/files/11644406/bagel.zip)

Note that commenting the following lines to remove the extra check, did let the dashboard use the csv and did not throw any other error I could detect.

https://github.com/neurobagel/proc_dash/blob/03ab3021252504a3ec78617166e7ea618970bab2/proc_dash/utility.py#L158-L159

**Comment by nikhil153** [comment]
@alyssadai - reviving this issue since it has become rather important for QPN dataset. 

Currently seeing this error when phenotypic digest-bagel is uploaded containing unequal number of sessions per `assessments` (i.e. pipelines). 

It's not possible for QPN to meet this criterion because of ad-hoc nature of visits. 

```
Error: The pipelines in the selected CSV do not have the same number of subjects and sessions. Please try again.
```
